### ISSUE TITLE
Lost search capability - live channels

### ISSUE THREAD

**Issue by randoms01** [Colossal1/plugin.video.sportie#4]
Hi Echo
Hope you enjoyed the wedding.
Since the last update Sportie has lost search  capability on live channels. On the previous version live channels were listed by country. And the live channel search bring up 672 results at present, on matter what search term is used in the add on settings.

I felt the feature of being able to sort live links on sportie on the live channels, set it apart from other third party addons available.

Keep up the good work

Randoms

**Comment by Colossal1** [comment]
Hello,

Unfortunatly at the moment the country lists have gone down from extbyte. Once they come back they will be added back to sportie.

Can you please confirm that the search terms do not work on the option that is now in live tv please.

**Comment by randoms01** [comment]
Hello

Thanks for your reply

I have tried the following search terms from the add-on setting, with the
check every link enabled. On Android boxes Kodi 16.2 & 17.
* beIN, sports
* Sky, sports
*Nbc
* Default no search terms
The results are not being filtered on the add-on 672 items Everytime.

Random

**Comment by Colossal1** [comment]
The terms should work on list a and b now.
