### ISSUE TITLE
Soccer steams error

### ISSUE THREAD

**Issue by randoms01** [Colossal1/plugin.video.sportie#6]
When soccer stream clicked error message "we do not support systems running Kodi 16 on this feature due to to issue. This issue is fixed on 17.0"

I am on Amazon fire box with kodi17.2 installed.

**Comment by Gujal00** [comment]
Site is down. Will need to wait and see if it comes back. Currently it is returning with Cloudflare page holder
This page (https://soccerstreams.net/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site

**Comment by randoms01** [comment]
Thanks Gujal for taking the time out to reply to my query. Finding nuggets
as I delve into the add-on further.

Randoms
